#!/bin/bash

docker run -it --rm \
--volume ${PWD}/newrpm:/root/rpmbuild/RPMS/noarch \
--volume ${HOME}/.gnupg:/root/.gnupg \
h0tbird/rpmbuild:latest /bin/bash -c "

  #---------
  # Install
  #---------

  mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
  gpg2 --output ~/RPM-GPG-KEY-booddies --armor --export marc.villacorta@gmail.com

  #-----------------
  # ~/booddies.repo
  #-----------------

  cat <<- EOF > ~/booddies.repo
	[booddies]
	name=Boot buddies. The bootstrapping fellowship.
	baseurl=http://yum-repositories.s3-website-eu-west-1.amazonaws.com/booddies
	gpgkey = file:///etc/pki/rpm-gpg/RPM-GPG-KEY-booddies
	gpgcheck=1
	enabled=1
	EOF

  #----------------------------------------
  # ~/rpmbuild/SPECS/booddies-release.spec
  #----------------------------------------

  cat <<- EOF > ~/rpmbuild/SPECS/booddies-release.spec
	Name: booddies-release
	Version: 1
	Release: 1
	License: Apache-2
	Summary: Boot buddies. The bootstrapping fellowship.
	Group: System Environment/Base
	BuildArch: noarch
	BuildRoot: %{_topdir}/%{name}-%{version}%{release}-root

	%description
	Boot buddies or booddies is a set of Docker containers used to bootstrapp
	a Mesos cluster using containers on top of CoreOS on top of KVM on top
	of bare metal. Although it can be used to boot any PXE compliant system,
	it is not intended to be a general purpose bootstrapping system.

	%install
	%{__rm} -rf %{buildroot}
	%{__mkdir_p} %{buildroot}/%{_sysconfdir}/yum.repos.d/
	%{__mkdir_p} %{buildroot}/%{_sysconfdir}/pki/rpm-gpg/
	%{__install} -p -D -m 0644 ~/booddies.repo %{buildroot}/%{_sysconfdir}/yum.repos.d/booddies.repo
	%{__install} -p -D -m 0644 ~/RPM-GPG-KEY-booddies %{buildroot}/%{_sysconfdir}/pki/rpm-gpg/RPM-GPG-KEY-booddies

	%files
	%defattr(-,root,root,-)
	%{_sysconfdir}/yum.repos.d/booddies.repo
	%{_sysconfdir}/pki/rpm-gpg/RPM-GPG-KEY-booddies

	%changelog
	* Thu Jun 11 2015 Marc Villacorta <marc.villacorta@gmail.com>
	- First release.
	EOF

  #-------------------
  # Build the package
  #-------------------

  rpmbuild -ba ~/rpmbuild/SPECS/booddies-release.spec"
